### ISSUE TITLE
Fill in committee member details

### ISSUE THREAD

**Issue by notexactlyawe** [ears-edi/earssite#4]
Everyone should have links to whatever things they feel and a short blurb.

**Comment by aga11313** [comment]
In commit 12ea4ec I improved the styling of the committe page and filled it with mock text. It now has to be replaced with short blurbs by every member of the committee.

**Comment by notexactlyawe** [comment]
Commit 6b45140 fixes most of this issue, but there are still things to be looked at.
 - @aga11313 website points to mine
 - @officialgupta social links are non-existent

**Comment by notexactlyawe** [comment]
c46ff81 Fixes @officialgupta social links

**Comment by aga11313** [comment]
Issue fixed in the 79418f4 commit.
